server:
  port: 9006
spring:
  application:
    name: tensquare-spit  #吐槽微服务
  data:
    mongodb:
      host: 192.168.242.149
      database: spitdb
  redis:
    host: 192.168.242.149
eureka:
  client:
    service-url:
      defaultZone: http://localhost:6868/eureka
  instance:
   prefer-ip-address: true