server:
  port: 12000
spring:
  application:
    name: tensquare-config  #配置中心微服务
  cloud:
    config:
      server:
        git:
          uri: https://gitee.com/chuanzhizhy/configee65.git
  rabbitmq:
    host: 192.168.242.149
management: #暴露触发消息总线的地址
  endpoints:
    web:
      exposure:
        include: bus-refresh